### ISSUE TITLE
parent gradle should be upgraded to cope with "licenses" w/o special behaviour

### ISSUE THREAD

**Issue by quotidian-ennui** [adaptris-labs/interlok-build-parent#22]
At the moment (c.f. https://github.com/adaptris-labs/interlok-solace-interop/pull/34) we need custom behaviour in each child gradle to handle any interlok licensing...

```
  // If running in a CI pipeline, then interlokLicense might be a secret so
  // we cater for that to 'check' work, w/o a license-docker.properties or similar.
  interlokLicense= project.findProperty('interlokLicense') ?: "false"
  interlokVerifySystemProperties = interlokLicense != "false" ? [ "interlok.license.key" : interlokLicense ] : [:]
```

Which means we can then in our CI Pipeline do the ORG_GRADLE dance.

```
    - name: Gradle check
      env:
        ORG_GRADLE_PROJECT_interlokLicense: ${{ secrets.INTERLOK_LICENSE_KEY }}
      run: |
        ./gradlew -Dorg.gradle.console=plain --no-daemon clean check
```

It would be good if the parent gradle did this automatically for us, which should be possible by changing https://github.com/adaptris-labs/interlok-build-parent/blob/645d60332e3a74072b3b7b8c2f1ff6dc895ced02/build.gradle#L221-L224
